// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Nubulus.Backend.Infraestructure.Pgsql;

#nullable disable

namespace nubulus.backend.api.Migrations
{
    [DbContext(typeof(PostgreDBContext))]
    [Migration("20251113085220_NewFields")]
    partial class NewFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Nubulus.Backend.Infraestructure.Pgsql.Models.Account", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("key");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("address");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("NumberId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("number_id");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("phone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)")
                        .HasColumnName("status");

                    b.HasKey("Key");

                    b.HasIndex("Id");

                    b.ToTable("accounts", (string)null);
                });

            modelBuilder.Entity("Nubulus.Backend.Infraestructure.Pgsql.Models.AccountUser", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("key");

                    b.Property<string>("AccountKey")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("account_key");

                    b.Property<string>("Creator")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)")
                        .HasColumnName("creator");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)")
                        .HasColumnName("status");

                    b.Property<string>("UserKey")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("user_key");

                    b.HasKey("Key");

                    b.HasIndex("AccountKey");

                    b.HasIndex("Id");

                    b.HasIndex("UserKey");

                    b.ToTable("accounts_users", (string)null);
                });

            modelBuilder.Entity("Nubulus.Backend.Infraestructure.Pgsql.Models.AuditRecord", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("key");

                    b.Property<string>("DataB64")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("data_b64");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_time");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("RecordKey")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("record_key");

                    b.Property<string>("RecordType")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)")
                        .HasColumnName("record_type");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("table_name");

                    b.Property<string>("User")
                        .IsRequired()
                        .HasMaxLength(264)
                        .HasColumnType("character varying(264)")
                        .HasColumnName("user");

                    b.HasKey("Key");

                    b.HasIndex("Id");

                    b.ToTable("audit_records", (string)null);
                });

            modelBuilder.Entity("Nubulus.Backend.Infraestructure.Pgsql.Models.User", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("key");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("full_name");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("password");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("phone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)")
                        .HasColumnName("status");

                    b.HasKey("Key");

                    b.HasIndex("Id");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Nubulus.Backend.Infraestructure.Pgsql.Models.AccountUser", b =>
                {
                    b.HasOne("Nubulus.Backend.Infraestructure.Pgsql.Models.Account", "Account")
                        .WithMany("AccountUsers")
                        .HasForeignKey("AccountKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Nubulus.Backend.Infraestructure.Pgsql.Models.User", "User")
                        .WithMany("AccountUsers")
                        .HasForeignKey("UserKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Nubulus.Backend.Infraestructure.Pgsql.Models.Account", b =>
                {
                    b.Navigation("AccountUsers");
                });

            modelBuilder.Entity("Nubulus.Backend.Infraestructure.Pgsql.Models.User", b =>
                {
                    b.Navigation("AccountUsers");
                });
#pragma warning restore 612, 618
        }
    }
}
